"""empty message

Revision ID: baf9c8eab1ee
Revises: 8fb44cd94f9f
Create Date: 2025-03-16 14:49:30.565246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf9c8eab1ee'
down_revision: Union[str, None] = '8fb44cd94f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birthday_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('birthday_day', sa.Date(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birthday_persons')
    # ### end Alembic commands ###
